// SONG
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const REQUEST_SONG = 'REQUEST_SONG';
export const RECEIVE_SONG = 'RECEIVE_SONG';
export const REQUEST_SONG_UPDATE = 'REQUEST_SONG_UPDATE';
export const RECEIVE_SONG_UPDATE = 'RECEIVE_SONG_UPDATE';

export const SEARCH = 'SEARCH';

// GLOBAL
export const EXPAND_MENU = 'EXPAND_MENU';
export const ON_SCROLL = 'ON_SCROLL';
export const GET_SONG_CONTAINER_POS = 'GET_SONG_CONTAINER_POS';
export const SET_SPLASHSCREEN_VISIBILITY = 'SET_SPLASHSCREEN_VISIBILITY';
export const TRIGGER_EDIT_MODE = 'TRIGGER_EDIT_MODE';
export const ON_DOCUMENT_SIZE_CHANGED = 'ON_DOCUMENT_SIZE_CHANGED';
